In [1]:
import pandas as pd
import numpy as np
from math import isnan

In [2]:
with open('PLmatches.csv') as open_file:
    df = pd.read_csv(open_file, index_col=0)

In [17]:
def get_prior_matches_by_stadium(match_stadium, season_num, match_timestamp, num_matches=38):
    all_prior_matches = df[(df['match_stadium'] == match_stadium)
                           &(df['season_num'] == season_num)
                          &(df['match_timestamp'] < match_timestamp)].sort_values(by='match_timestamp')
    
    return all_prior_matches[-num_matches:]

def get_mean_value(data, col_name):
    values = []
    for row_index in data.index:
        values.append(data.loc[row_index, col_name])
    
    return np.mean(values)

In [23]:
def get_stadium_attendance_delta(row):
    match_stadium = row['match_stadium']
    season_num = row['season_num']
    cur_timestamp = row['match_timestamp']
    
    df_lastgame = get_prior_matches_by_stadium(match_stadium, season_num, cur_timestamp, 1)
    print(f'df_lastgame index: {df_lastgame.index}')
    
    cur_attendance = row['match_attendance']
    lastgame_attendance = get_mean_value(df_lastgame, 'match_attendance')
    
    return cur_attendance - lastgame_attendance

In [24]:
get_stadium_attendance_delta(df.loc[22700, :])

df_lastgame index: Int64Index([22680], dtype='int64')

-28136.0

In [20]:
df.sample(5)

,hometeam_name,awayteam_name,home_goals,away_goals,match_date,match_timestamp,match_referee,match_stadium,match_attendance,home_possession,...,away_matchesplayed,home_goaldifferential,away_goaldifferential,home_leaguepts,away_leaguepts,matchweek,stadium_capacity,season_num,home_prior_leaguerank,away_prior_leaguerank
14074,Manchester United,Manchester City,1,2,Sat 10 Sep 2016,1473507000000,Mark Clattenburg,"Old Trafford, Manchester",75272.0,39.9,...,4,4,7,9,12,4,74994,11,3.0,1.0
14234,Middlesbrough,Leicester City,0,0,Mon 2 Jan 2017,1483360200000,Robert Madley,"Riverside Stadium, Middlesbrough",32437.0,62.4,...,20,-5,-7,19,21,20,34000,11,16.0,15.0
5797,Liverpool,Chelsea,2,0,Sat 20 Jan 2007,1169297100000,Rob Styles,"Anfield, Liverpool",44969.0,45.5,...,24,21,22,46,51,24,54074,1,3.0,2.0
22644,Huddersfield Town,Crystal Palace,0,2,Sat 17 Mar 2018,1521298800000,Mike Dean,"John Smith's Stadium, Huddersfield",23980.0,54.6,...,31,-27,-18,31,30,31,24121,12,15.0,18.0
7829,Bolton Wanderers,West Bromwich Albion,2,2,Sun 6 May 2012,1336309200000,Kevin Friend,"Macron Stadium, Bolton",25662.0,37.6,...,37,-31,-6,35,47,36,28723,6,18.0,10.0

In [21]:
df['attendance_delta'] = df.apply(get_stadium_attendance_delta, axis=1)

/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [22]:
df['attendance_delta']

5567         NaN
5568         NaN
5569         NaN
5570         NaN
5571         NaN
5572         NaN
5573         NaN
5574         NaN
5575         NaN
5576         NaN
5577         NaN
5578         NaN
5579         NaN
5580         NaN
5581         NaN
5582         NaN
5583         NaN
5584         NaN
5585     -1739.0
5586      -247.0
5587         NaN
5588      3485.0
5589       253.0
5590      1109.0
5591         NaN
5592     -2188.0
5593     -2617.0
5594     -4435.0
5595       -16.0
5596     -1759.0
          ...
22692    -1805.0
22693     1094.0
22694      160.0
22695      296.0
22696      -60.0
22697       73.0
22698       14.0
22699      -33.0
22700   -28136.0
22701      109.0
22702      118.0
22703     -132.0
22704      171.0
22705      -10.0
22706     -836.0
22707      853.0
22708      -37.0
22709      155.0
22710      -26.0
22711     -835.0
22712     1261.0
22713     -393.0
22714        1.0
22715    -2503.0
22716       14.0
22717       11.0
22718      104.0
22719     -185.0
22720    22918.0
22721       24.0
Name: attendance_delta, Length: 4559, dtype: float64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4559 entries, 5567 to 22721
Data columns (total 47 columns):
hometeam_name            4559 non-null object
awayteam_name            4559 non-null object
home_goals               4559 non-null int64
away_goals               4559 non-null int64
match_date               4559 non-null object
match_timestamp          4559 non-null int64
match_referee            4559 non-null object
match_stadium            4559 non-null object
match_attendance         4013 non-null float64
home_possession          4559 non-null float64
away_possession          4559 non-null float64
home_shotsontarget       4559 non-null int64
away_shotsontarget       4559 non-null int64
home_shots               4559 non-null int64
away_shots               4559 non-null int64
home_touches             4559 non-null int64
away_touches             4559 non-null int64
home_passes              4559 non-null int64
away_passes              4559 non-null int64
home_tackles             4559 non-null int64
away_tackles             4559 non-null int64
home_clearances          4559 non-null int64
away_clearances          4559 non-null int64
home_corners             4559 non-null int64
away_corners             4559 non-null int64
home_offsides            4559 non-null int64
away_offsides            4559 non-null int64
home_yellowcards         4559 non-null int64
away_yellowcards         4559 non-null int64
home_redcards            4559 non-null int64
away_redcards            4559 non-null int64
home_fouls               4559 non-null int64
away_fouls               4559 non-null int64
home_leaguerank          4559 non-null int64
away_leaguerank          4559 non-null int64
home_matchesplayed       4559 non-null int64
away_matchesplayed       4559 non-null int64
home_goaldifferential    4559 non-null int64
away_goaldifferential    4559 non-null int64
home_leaguepts           4559 non-null int64
away_leaguepts           4559 non-null int64
matchweek                4559 non-null int64
stadium_capacity         4559 non-null int64
season_num               4559 non-null int64
home_prior_leaguerank    4439 non-null float64
away_prior_leaguerank    4439 non-null float64
attendance_delta         3768 non-null float64
dtypes: float64(6), int64(36), object(5)
memory usage: 1.8+ MB

In [26]:
with open('PLmatches.csv', 'w') as open_file:
    df.to_csv(open_file)