In [69]:
import pandas as pd
import numpy as np
from math import isnan

In [2]:
with open('PLmatches.csv') as open_file:
    df = pd.read_csv(open_file, index_col=0)

In [3]:
df

,hometeam_name,awayteam_name,home_goals,away_goals,match_date,match_timestamp,match_referee,match_stadium,match_attendance,home_possession,...,away_leaguerank,home_matchesplayed,away_matchesplayed,home_goaldifferential,away_goaldifferential,home_leaguepts,away_leaguepts,matchweek,stadium_capacity,season_num
5567,Arsenal,Aston Villa,1,1,Sat 19 Aug 2006,1155996000000,Graham Poll,"Emirates Stadium, London",60023.0,72.9,...,10,1,1,0,0,1,1,1,59867,1
5568,Bolton Wanderers,Tottenham Hotspur,2,0,Sat 19 Aug 2006,1156004100000,Phil Dowd,"Macron Stadium, Bolton",22899.0,37.8,...,17,1,1,2,-2,3,0,1,28723,1
5569,Everton,Watford,2,1,Sat 19 Aug 2006,1155996000000,Peter Walton,"Goodison Park, Liverpool",39691.0,47.0,...,14,1,1,1,-1,3,0,1,39572,1
5570,Newcastle United,Wigan Athletic,2,1,Sat 19 Aug 2006,1155996000000,Martin Atkinson,"Sports Direct Arena, Newcastle",52227.0,55.3,...,15,1,1,1,-1,3,0,1,52354,1
5571,Portsmouth,Blackburn Rovers,3,0,Sat 19 Aug 2006,1155996000000,Alan Wiley,"Fratton Park, Portsmouth",19502.0,44.3,...,18,1,1,3,-3,3,0,1,19699,1
5572,Reading,Middlesbrough,3,2,Sat 19 Aug 2006,1155996000000,Mark Halsey,"Madejski Stadium, Reading",23802.0,52.1,...,13,1,1,1,-1,3,0,1,24161,1
5573,Sheffield United,Liverpool,1,1,Sat 19 Aug 2006,1155987900000,Rob Styles,"Bramall Lane, Sheffield",31726.0,41.9,...,11,1,1,0,0,1,1,1,32702,1
5574,West Ham United,Charlton Athletic,3,1,Sat 19 Aug 2006,1155996000000,Howard Webb,"Boleyn Ground, London",34704.0,62.4,...,16,1,1,2,-2,3,0,1,35016,1
5575,Chelsea,Manchester City,3,0,Sun 20 Aug 2006,1156086000000,Steve Bennett,"Stamford Bridge, London",41814.0,58.1,...,19,1,1,3,-3,3,0,1,41631,1
5576,Manchester United,Fulham,5,1,Sun 20 Aug 2006,1156077000000,Andre Marriner,"Old Trafford, Manchester",75115.0,65.0,...,20,1,1,4,-4,3,0,1,74994,1
5577,Tottenham Hotspur,Sheffield United,2,0,Tue 22 Aug 2006,1156273200000,Peter Walton,"White Hart Lane, London",35287.0,56.1,...,15,2,2,0,-2,3,1,2,36284,1
5578,Watford,West Ham United,1,1,Tue 22 Aug 2006,1156272300000,Martin Atkinson,"Vicarage Road, Watford",18344.0,52.5,...,3,2,2,-1,2,1,4,2,21577,1
5579,Aston Villa,Reading,2,1,Wed 23 Aug 2006,1156358700000,Lee Mason,"Villa Park, Birmingham",37329.0,56.7,...,10,2,2,1,0,4,3,2,42682,1
5580,Blackburn Rovers,Everton,1,1,Wed 23 Aug 2006,1156359600000,Uriah Rennie,"Ewood Park, Blackburn",22015.0,47.9,...,6,2,2,-3,1,1,4,2,31367,1
5581,Charlton Athletic,Manchester United,0,3,Wed 23 Aug 2006,1156359600000,Chris Foy,"The Valley, London",25412.0,40.7,...,1,2,2,-5,7,0,6,2,27111,1
5582,Fulham,Bolton Wanderers,1,1,Wed 23 Aug 2006,1156359600000,Alan Wiley,"Craven Cottage, London",18559.0,61.1,...,4,2,2,-4,2,1,4,2,25700,1
5583,Manchester City,Portsmouth,0,0,Wed 23 Aug 2006,1156358700000,Dermot Gallagher,"Etihad Stadium, Manchester",37214.0,53.9,...,2,2,2,-3,3,1,4,2,55097,1
5584,Middlesbrough,Chelsea,2,1,Wed 23 Aug 2006,1156359600000,Howard Webb,"Riverside Stadium, Middlesbrough",29269.0,46.4,...,7,2,2,0,2,3,3,2,34000,1
5585,Charlton Athletic,Bolton Wanderers,2,0,Sat 26 Aug 2006,1156600800000,Mike Dean,"The Valley, London",23673.0,42.9,...,8,3,3,-3,0,3,4,3,27111,1
5586,Fulham,Sheffield United,1,0,Sat 26 Aug 2006,1156600800000,Graham Poll,"Craven Cottage, London",18312.0,61.0,...,19,3,3,-3,-3,4,1,3,25700,1
5587,Liverpool,West Ham United,2,1,Sat 26 Aug 2006,1156592700000,Alan Wiley,"Anfield, Liverpool",45262.0,54.7,...,6,2,3,1,1,4,4,3,54074,1
5588,Manchester City,Arsenal,1,0,Sat 26 Aug 2006,1156608900000,Uriah Rennie,"Etihad Stadium, Manchester",40699.0,37.8,...,17,3,2,-2,-1,4,1,3,55097,1
5589,Tottenham Hotspur,Everton,0,2,Sat 26 Aug 2006,1156600800000,Mark Halsey,"White Hart Lane, London",35540.0,56.3,...,4,3,3,-2,3,3,7,3,36284,1
5590,Watford,Manchester United,1,2,Sat 26 Aug 2006,1156600800000,Phil Dowd,"Vicarage Road, Watford",19453.0,40.5,...,1,3,3,-2,8,1,9,3,21577,1
5591,Wigan Athletic,Reading,1,0,Sat 26 Aug 2006,1156600800000,Mike Riley,"DW Stadium, Wigan",14834.0,48.1,...,12,2,3,0,-1,3,3,3,25138,1
5592,Aston Villa,Newcastle United,2,0,Sun 27 Aug 2006,1156683600000,Howard Webb,"Villa Park, Birmingham",35141.0,45.2,...,13,3,2,3,-1,7,3,3,42682,1
5593,Blackburn Rovers,Chelsea,0,2,Sun 27 Aug 2006,1156690800000,Mark Clattenburg,"Ewood Park, Blackburn",19398.0,47.8,...,5,3,3,-5,4,1,6,3,31367,1
5594,Middlesbrough,Portsmouth,0,4,Mon 28 Aug 2006,1156791600000,Chris Foy,"Riverside Stadium, Middlesbrough",24834.0,64.2,...,2,3,3,-4,7,3,7,3,34000,1
5595,Arsenal,Middlesbrough,1,1,Sat 9 Sep 2006,1157810400000,Rob Styles,"Emirates Stadium, London",60007.0,69.2,...,12,3,4,-1,-4,2,4,4,59867,1
5596,Bolton Wanderers,Watford,1,0,Sat 9 Sep 2006,1157810400000,Mark Clattenburg,"Macron Stadium, Bolton",21140.0,53.8,...,20,4,4,1,-3,7,1,4,28723,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Burnley,Brighton and Hove Albion,0,0,Sat 28 Apr 2018,1524924000000,Roger East,"Turf Moor, Burnley",19459.0,44.5,...,14,36,35,3,-15,54,37,36,21401,12
22693,Crystal Palace,Leicester City,5,0,Sat 28 Apr 2018,1524924000000,Mike Dean,"Selhurst Park, London",25750.0,50.5,...,9,36,35,-13,-3,38,44,36,26074,12
22694,Huddersfield Town,Everton,0,2,Sat 28 Apr 2018,1524924000000,Lee Probert,"John Smith's Stadium, Huddersfield",24121.0,53.7,...,8,35,36,-29,-12,35,48,36,24121,12
22695,Liverpool,Stoke City,0,0,Sat 28 Apr 2018,1524915000000,Andre Marriner,"Anfield, Liverpool",53255.0,71.9,...,19,36,36,43,-33,72,30,36,54074,12
22696,Manchester United,Arsenal,2,1,Sun 29 Apr 2018,1525015800000,Kevin Friend,"Old Trafford, Manchester",75035.0,59.2,...,6,35,35,40,19,77,57,36,74994,12
22697,Newcastle United,West Bromwich Albion,0,1,Sat 28 Apr 2018,1524924000000,David Coote,"St. James' Park, Newcastle",52283.0,63.5,...,20,35,36,-9,-24,41,28,36,52354,12
22698,Southampton,AFC Bournemouth,2,1,Sat 28 Apr 2018,1524924000000,Anthony Taylor,"St. Mary's Stadium, Southampton",31778.0,40.3,...,12,35,36,-19,-18,32,38,36,32505,12
22699,Swansea City,Chelsea,0,1,Sat 28 Apr 2018,1524933000000,Jonathan Moss,"Liberty Stadium, Swansea",20900.0,51.1,...,5,35,35,-25,26,33,66,36,21088,12
22700,Tottenham Hotspur,Watford,2,0,Mon 30 Apr 2018,1525114800000,Michael Oliver,"Wembley Stadium, London",52675.0,61.5,...,13,35,36,37,-20,71,38,36,90000,12
22701,West Ham United,Manchester City,1,4,Sun 29 Apr 2018,1525007700000,Neil Swarbrick,"London Stadium, London",56904.0,24.6,...,1,35,35,-24,76,35,93,36,57000,12
22702,Arsenal,Burnley,5,0,Sun 6 May 2018,1525620600000,Andre Marriner,"Emirates Stadium, London",59540.0,63.6,...,7,37,37,22,-2,60,54,37,59867,12
22703,AFC Bournemouth,Swansea City,1,0,Sat 5 May 2018,1525528800000,Kevin Friend,"Vitality Stadium, Bournemouth",10820.0,45.2,...,18,37,37,-17,-27,41,33,37,11360,12
22704,Brighton and Hove Albion,Manchester United,1,0,Fri 4 May 2018,1525460400000,Craig Pawson,"Amex Stadium, Falmer",30611.0,31.7,...,2,37,37,-16,39,40,78,37,30750,12
22705,Chelsea,Liverpool,1,0,Sun 6 May 2018,1525620600000,Anthony Taylor,"Stamford Bridge, London",41314.0,31.6,...,4,37,37,27,42,70,72,37,41631,12
22706,Everton,Southampton,1,1,Sat 5 May 2018,1525537800000,Jonathan Moss,"Goodison Park, Liverpool",38225.0,54.4,...,17,37,37,-12,-18,49,36,37,39572,12
22707,Leicester City,West Ham United,0,2,Sat 5 May 2018,1525528800000,Chris Kavanagh,"King Power Stadium, Leicester",32013.0,54.0,...,15,37,37,-3,-22,47,39,37,32312,12
22708,Manchester City,Huddersfield Town,0,0,Sun 6 May 2018,1525609800000,Mike Dean,"Etihad Stadium, Manchester",54350.0,79.2,...,16,37,37,78,-29,97,37,37,55097,12
22709,Stoke City,Crystal Palace,1,2,Sat 5 May 2018,1525519800000,Martin Atkinson,"bet365 Stadium, Stoke",29687.0,41.1,...,11,37,37,-34,-12,30,41,37,30089,12
22710,Watford,Newcastle United,2,1,Sat 5 May 2018,1525528800000,Roger East,"Vicarage Road, Watford",20375.0,39.2,...,10,37,37,-19,-11,41,41,37,21577,12
22711,West Bromwich Albion,Tottenham Hotspur,1,0,Sat 5 May 2018,1525528800000,Mike Jones,"The Hawthorns, West Bromwich",23685.0,26.2,...,3,37,37,-23,37,31,74,37,26688,12
22712,Burnley,AFC Bournemouth,1,2,Sun 13 May 2018,1526220000000,Paul Tierney,"Turf Moor, Burnley",20720.0,51.4,...,12,38,38,-3,-16,54,44,38,21401,12
22713,Crystal Palace,West Bromwich Albion,2,0,Sun 13 May 2018,1526220000000,Jonathan Moss,"Selhurst Park, London",25357.0,59.2,...,20,38,38,-10,-25,44,31,38,26074,12
22714,Huddersfield Town,Arsenal,0,1,Sun 13 May 2018,1526220000000,Michael Oliver,"John Smith's Stadium, Huddersfield",24122.0,45.0,...,6,38,38,-30,23,37,63,38,24121,12
22715,Liverpool,Brighton and Hove Albion,4,0,Sun 13 May 2018,1526220000000,Kevin Friend,"Anfield, Liverpool",50752.0,72.3,...,15,38,38,46,-20,75,40,38,54074,12
22716,Manchester United,Watford,1,0,Sun 13 May 2018,1526220000000,Lee Mason,"Old Trafford, Manchester",75049.0,51.4,...,14,38,38,40,-20,81,41,38,74994,12
22717,Newcastle United,Chelsea,3,0,Sun 13 May 2018,1526220000000,Martin Atkinson,"St. James' Park, Newcastle",52294.0,41.9,...,5,38,38,-8,24,44,70,38,52354,12
22718,Southampton,Manchester City,0,1,Sun 13 May 2018,1526220000000,Andre Marriner,"St. Mary's Stadium, Southampton",31882.0,30.3,...,1,38,38,-19,79,36,100,38,32505,12
22719,Swansea City,Stoke City,1,2,Sun 13 May 2018,1526220000000,Anthony Taylor,"Liberty Stadium, Swansea",20673.0,57.6,...,19,38,38,-28,-33,33,33,38,21088,12
22720,Tottenham Hotspur,Leicester City,5,4,Sun 13 May 2018,1526220000000,Craig Pawson,"Wembley Stadium, London",77841.0,64.0,...,9,38,38,38,-4,77,47,38,90000,12
22721,West Ham United,Everton,3,1,Sun 13 May 2018,1526220000000,Graham Scott,"London Stadium, London",56926.0,56.6,...,8,38,38,-20,-14,42,49,38,57000,12

In [39]:
def get_prior_matches(team_name, season_num, match_timestamp, num_matches=38):
    all_prior_matches = df[((df['hometeam_name'] == team_name)|(df['awayteam_name'] == team_name))
                           &(df['season_num'] == season_num)
                          &(df['match_timestamp'] < match_timestamp)].sort_values(by='match_timestamp')
    
    return all_prior_matches[-num_matches:]

get_prior_matches('Arsenal', 1, 1455996000000, 30)

5656
5675
5684
5686
5697
5708
5711
5732
5735
5736
5746
5763
5772
5783
5785
5803
5820
5832
5844
5854
5865
5869
5878
5890
5892
5900
5910
5923
5933
5943

In [84]:
def get_mean_value_by_team(data, team_name, col_name):
    values = []
    for row_index in data.index:
        if data.loc[row_index, 'hometeam_name'] != team_name and data.loc[row_index, 'awayteam_name'] != team_name:
            continue
        team_loc = 'home' if data.loc[row_index, 'hometeam_name'] == team_name else 'away'
        values.append(data.loc[row_index, '_'.join([team_loc, col_name])])
    
    return np.mean(values)

def get_values_by_team(data, team_name, col_name):
    values = []
    for row_index in data.index:
        if data.loc[row_index, 'hometeam_name'] != team_name and data.loc[row_index, 'awayteam_name'] != team_name:
            continue
        team_loc = 'home' if data.loc[row_index, 'hometeam_name'] == team_name else 'away'
        values.append(data.loc[row_index, '_'.join([team_loc, col_name])])
    
    return values

In [ ]:
col_ids = {}

In [82]:
df['home_prior_leaguerank'] = 0

In [81]:
df.drop('home_last_leaguerank', axis=1, inplace=True)

In [98]:
df

,hometeam_name,awayteam_name,home_goals,away_goals,match_date,match_timestamp,match_referee,match_stadium,match_attendance,home_possession,...,home_matchesplayed,away_matchesplayed,home_goaldifferential,away_goaldifferential,home_leaguepts,away_leaguepts,matchweek,stadium_capacity,season_num,home_prior_leaguerank
5567,Arsenal,Aston Villa,1,1,Sat 19 Aug 2006,1155996000000,Graham Poll,"Emirates Stadium, London",60023.0,72.9,...,1,1,0,0,1,1,1,59867,1,NaN
5568,Bolton Wanderers,Tottenham Hotspur,2,0,Sat 19 Aug 2006,1156004100000,Phil Dowd,"Macron Stadium, Bolton",22899.0,37.8,...,1,1,2,-2,3,0,1,28723,1,NaN
5569,Everton,Watford,2,1,Sat 19 Aug 2006,1155996000000,Peter Walton,"Goodison Park, Liverpool",39691.0,47.0,...,1,1,1,-1,3,0,1,39572,1,NaN
5570,Newcastle United,Wigan Athletic,2,1,Sat 19 Aug 2006,1155996000000,Martin Atkinson,"Sports Direct Arena, Newcastle",52227.0,55.3,...,1,1,1,-1,3,0,1,52354,1,NaN
5571,Portsmouth,Blackburn Rovers,3,0,Sat 19 Aug 2006,1155996000000,Alan Wiley,"Fratton Park, Portsmouth",19502.0,44.3,...,1,1,3,-3,3,0,1,19699,1,NaN
5572,Reading,Middlesbrough,3,2,Sat 19 Aug 2006,1155996000000,Mark Halsey,"Madejski Stadium, Reading",23802.0,52.1,...,1,1,1,-1,3,0,1,24161,1,NaN
5573,Sheffield United,Liverpool,1,1,Sat 19 Aug 2006,1155987900000,Rob Styles,"Bramall Lane, Sheffield",31726.0,41.9,...,1,1,0,0,1,1,1,32702,1,NaN
5574,West Ham United,Charlton Athletic,3,1,Sat 19 Aug 2006,1155996000000,Howard Webb,"Boleyn Ground, London",34704.0,62.4,...,1,1,2,-2,3,0,1,35016,1,NaN
5575,Chelsea,Manchester City,3,0,Sun 20 Aug 2006,1156086000000,Steve Bennett,"Stamford Bridge, London",41814.0,58.1,...,1,1,3,-3,3,0,1,41631,1,NaN
5576,Manchester United,Fulham,5,1,Sun 20 Aug 2006,1156077000000,Andre Marriner,"Old Trafford, Manchester",75115.0,65.0,...,1,1,4,-4,3,0,1,74994,1,NaN
5577,Tottenham Hotspur,Sheffield United,2,0,Tue 22 Aug 2006,1156273200000,Peter Walton,"White Hart Lane, London",35287.0,56.1,...,2,2,0,-2,3,1,2,36284,1,17.0
5578,Watford,West Ham United,1,1,Tue 22 Aug 2006,1156272300000,Martin Atkinson,"Vicarage Road, Watford",18344.0,52.5,...,2,2,-1,2,1,4,2,21577,1,14.0
5579,Aston Villa,Reading,2,1,Wed 23 Aug 2006,1156358700000,Lee Mason,"Villa Park, Birmingham",37329.0,56.7,...,2,2,1,0,4,3,2,42682,1,10.0
5580,Blackburn Rovers,Everton,1,1,Wed 23 Aug 2006,1156359600000,Uriah Rennie,"Ewood Park, Blackburn",22015.0,47.9,...,2,2,-3,1,1,4,2,31367,1,18.0
5581,Charlton Athletic,Manchester United,0,3,Wed 23 Aug 2006,1156359600000,Chris Foy,"The Valley, London",25412.0,40.7,...,2,2,-5,7,0,6,2,27111,1,16.0
5582,Fulham,Bolton Wanderers,1,1,Wed 23 Aug 2006,1156359600000,Alan Wiley,"Craven Cottage, London",18559.0,61.1,...,2,2,-4,2,1,4,2,25700,1,20.0
5583,Manchester City,Portsmouth,0,0,Wed 23 Aug 2006,1156358700000,Dermot Gallagher,"Etihad Stadium, Manchester",37214.0,53.9,...,2,2,-3,3,1,4,2,55097,1,19.0
5584,Middlesbrough,Chelsea,2,1,Wed 23 Aug 2006,1156359600000,Howard Webb,"Riverside Stadium, Middlesbrough",29269.0,46.4,...,2,2,0,2,3,3,2,34000,1,13.0
5585,Charlton Athletic,Bolton Wanderers,2,0,Sat 26 Aug 2006,1156600800000,Mike Dean,"The Valley, London",23673.0,42.9,...,3,3,-3,0,3,4,3,27111,1,20.0
5586,Fulham,Sheffield United,1,0,Sat 26 Aug 2006,1156600800000,Graham Poll,"Craven Cottage, London",18312.0,61.0,...,3,3,-3,-3,4,1,3,25700,1,18.0
5587,Liverpool,West Ham United,2,1,Sat 26 Aug 2006,1156592700000,Alan Wiley,"Anfield, Liverpool",45262.0,54.7,...,2,3,1,1,4,4,3,54074,1,11.0
5588,Manchester City,Arsenal,1,0,Sat 26 Aug 2006,1156608900000,Uriah Rennie,"Etihad Stadium, Manchester",40699.0,37.8,...,3,2,-2,-1,4,1,3,55097,1,17.0
5589,Tottenham Hotspur,Everton,0,2,Sat 26 Aug 2006,1156600800000,Mark Halsey,"White Hart Lane, London",35540.0,56.3,...,3,3,-2,3,3,7,3,36284,1,11.0
5590,Watford,Manchester United,1,2,Sat 26 Aug 2006,1156600800000,Phil Dowd,"Vicarage Road, Watford",19453.0,40.5,...,3,3,-2,8,1,9,3,21577,1,14.0
5591,Wigan Athletic,Reading,1,0,Sat 26 Aug 2006,1156600800000,Mike Riley,"DW Stadium, Wigan",14834.0,48.1,...,2,3,0,-1,3,3,3,25138,1,15.0
5592,Aston Villa,Newcastle United,2,0,Sun 27 Aug 2006,1156683600000,Howard Webb,"Villa Park, Birmingham",35141.0,45.2,...,3,2,3,-1,7,3,3,42682,1,5.0
5593,Blackburn Rovers,Chelsea,0,2,Sun 27 Aug 2006,1156690800000,Mark Clattenburg,"Ewood Park, Blackburn",19398.0,47.8,...,3,3,-5,4,1,6,3,31367,1,16.0
5594,Middlesbrough,Portsmouth,0,4,Mon 28 Aug 2006,1156791600000,Chris Foy,"Riverside Stadium, Middlesbrough",24834.0,64.2,...,3,3,-4,7,3,7,3,34000,1,9.0
5595,Arsenal,Middlesbrough,1,1,Sat 9 Sep 2006,1157810400000,Rob Styles,"Emirates Stadium, London",60007.0,69.2,...,3,4,-1,-4,2,4,4,59867,1,17.0
5596,Bolton Wanderers,Watford,1,0,Sat 9 Sep 2006,1157810400000,Mark Clattenburg,"Macron Stadium, Bolton",21140.0,53.8,...,4,4,1,-3,7,1,4,28723,1,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Burnley,Brighton and Hove Albion,0,0,Sat 28 Apr 2018,1524924000000,Roger East,"Turf Moor, Burnley",19459.0,44.5,...,36,35,3,-15,54,37,36,21401,12,7.0
22693,Crystal Palace,Leicester City,5,0,Sat 28 Apr 2018,1524924000000,Mike Dean,"Selhurst Park, London",25750.0,50.5,...,36,35,-13,-3,38,44,36,26074,12,14.0
22694,Huddersfield Town,Everton,0,2,Sat 28 Apr 2018,1524924000000,Lee Probert,"John Smith's Stadium, Huddersfield",24121.0,53.7,...,35,36,-29,-12,35,48,36,24121,12,15.0
22695,Liverpool,Stoke City,0,0,Sat 28 Apr 2018,1524915000000,Andre Marriner,"Anfield, Liverpool",53255.0,71.9,...,36,36,43,-33,72,30,36,54074,12,3.0
22696,Manchester United,Arsenal,2,1,Sun 29 Apr 2018,1525015800000,Kevin Friend,"Old Trafford, Manchester",75035.0,59.2,...,35,35,40,19,77,57,36,74994,12,2.0
22697,Newcastle United,West Bromwich Albion,0,1,Sat 28 Apr 2018,1524924000000,David Coote,"St. James' Park, Newcastle",52283.0,63.5,...,35,36,-9,-24,41,28,36,52354,12,10.0
22698,Southampton,AFC Bournemouth,2,1,Sat 28 Apr 2018,1524924000000,Anthony Taylor,"St. Mary's Stadium, Southampton",31778.0,40.3,...,35,36,-19,-18,32,38,36,32505,12,18.0
22699,Swansea City,Chelsea,0,1,Sat 28 Apr 2018,1524933000000,Jonathan Moss,"Liberty Stadium, Swansea",20900.0,51.1,...,35,35,-25,26,33,66,36,21088,12,17.0
22700,Tottenham Hotspur,Watford,2,0,Mon 30 Apr 2018,1525114800000,Michael Oliver,"Wembley Stadium, London",52675.0,61.5,...,35,36,37,-20,71,38,36,90000,12,4.0
22701,West Ham United,Manchester City,1,4,Sun 29 Apr 2018,1525007700000,Neil Swarbrick,"London Stadium, London",56904.0,24.6,...,35,35,-24,76,35,93,36,57000,12,15.0
22702,Arsenal,Burnley,5,0,Sun 6 May 2018,1525620600000,Andre Marriner,"Emirates Stadium, London",59540.0,63.6,...,37,37,22,-2,60,54,37,59867,12,6.0
22703,AFC Bournemouth,Swansea City,1,0,Sat 5 May 2018,1525528800000,Kevin Friend,"Vitality Stadium, Bournemouth",10820.0,45.2,...,37,37,-17,-27,41,33,37,11360,12,12.0
22704,Brighton and Hove Albion,Manchester United,1,0,Fri 4 May 2018,1525460400000,Craig Pawson,"Amex Stadium, Falmer",30611.0,31.7,...,37,37,-16,39,40,78,37,30750,12,14.0
22705,Chelsea,Liverpool,1,0,Sun 6 May 2018,1525620600000,Anthony Taylor,"Stamford Bridge, London",41314.0,31.6,...,37,37,27,42,70,72,37,41631,12,5.0
22706,Everton,Southampton,1,1,Sat 5 May 2018,1525537800000,Jonathan Moss,"Goodison Park, Liverpool",38225.0,54.4,...,37,37,-12,-18,49,36,37,39572,12,8.0
22707,Leicester City,West Ham United,0,2,Sat 5 May 2018,1525528800000,Chris Kavanagh,"King Power Stadium, Leicester",32013.0,54.0,...,37,37,-3,-22,47,39,37,32312,12,9.0
22708,Manchester City,Huddersfield Town,0,0,Sun 6 May 2018,1525609800000,Mike Dean,"Etihad Stadium, Manchester",54350.0,79.2,...,37,37,78,-29,97,37,37,55097,12,1.0
22709,Stoke City,Crystal Palace,1,2,Sat 5 May 2018,1525519800000,Martin Atkinson,"bet365 Stadium, Stoke",29687.0,41.1,...,37,37,-34,-12,30,41,37,30089,12,19.0
22710,Watford,Newcastle United,2,1,Sat 5 May 2018,1525528800000,Roger East,"Vicarage Road, Watford",20375.0,39.2,...,37,37,-19,-11,41,41,37,21577,12,13.0
22711,West Bromwich Albion,Tottenham Hotspur,1,0,Sat 5 May 2018,1525528800000,Mike Jones,"The Hawthorns, West Bromwich",23685.0,26.2,...,37,37,-23,37,31,74,37,26688,12,20.0
22712,Burnley,AFC Bournemouth,1,2,Sun 13 May 2018,1526220000000,Paul Tierney,"Turf Moor, Burnley",20720.0,51.4,...,38,38,-3,-16,54,44,38,21401,12,7.0
22713,Crystal Palace,West Bromwich Albion,2,0,Sun 13 May 2018,1526220000000,Jonathan Moss,"Selhurst Park, London",25357.0,59.2,...,38,38,-10,-25,44,31,38,26074,12,11.0
22714,Huddersfield Town,Arsenal,0,1,Sun 13 May 2018,1526220000000,Michael Oliver,"John Smith's Stadium, Huddersfield",24122.0,45.0,...,38,38,-30,23,37,63,38,24121,12,16.0
22715,Liverpool,Brighton and Hove Albion,4,0,Sun 13 May 2018,1526220000000,Kevin Friend,"Anfield, Liverpool",50752.0,72.3,...,38,38,46,-20,75,40,38,54074,12,4.0
22716,Manchester United,Watford,1,0,Sun 13 May 2018,1526220000000,Lee Mason,"Old Trafford, Manchester",75049.0,51.4,...,38,38,40,-20,81,41,38,74994,12,2.0
22717,Newcastle United,Chelsea,3,0,Sun 13 May 2018,1526220000000,Martin Atkinson,"St. James' Park, Newcastle",52294.0,41.9,...,38,38,-8,24,44,70,38,52354,12,10.0
22718,Southampton,Manchester City,0,1,Sun 13 May 2018,1526220000000,Andre Marriner,"St. Mary's Stadium, Southampton",31882.0,30.3,...,38,38,-19,79,36,100,38,32505,12,17.0
22719,Swansea City,Stoke City,1,2,Sun 13 May 2018,1526220000000,Anthony Taylor,"Liberty Stadium, Swansea",20673.0,57.6,...,38,38,-28,-33,33,33,38,21088,12,18.0
22720,Tottenham Hotspur,Leicester City,5,4,Sun 13 May 2018,1526220000000,Craig Pawson,"Wembley Stadium, London",77841.0,64.0,...,38,38,38,-4,77,47,38,90000,12,3.0
22721,West Ham United,Everton,3,1,Sun 13 May 2018,1526220000000,Graham Scott,"London Stadium, London",56926.0,56.6,...,38,38,-20,-14,42,49,38,57000,12,15.0

In [90]:
df_ars_1 = get_prior_matches('Arsenal', 1, 1855996000000, 39)

In [63]:
test = get_mean_value_by_team(df_ars_1, 'Arsenal', 'goals')

/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [70]:
test if not isnan(test) else 'nothing there!'

'nothing there!'

In [96]:
def get_prior_home_leaguerank(row):
    team_name = row['hometeam_name']
    season_num = row['season_num']
    cur_timestamp = row['match_timestamp']
    
    df_lastgame = get_prior_matches(team_name, season_num, cur_timestamp, 1)
    
    return get_mean_value_by_team(df_lastgame, team_name, 'leaguerank')

def get_prior_away_leaguerank(row):
    team_name = row['awayteam_name']
    season_num = row['season_num']
    cur_timestamp = row['match_timestamp']
    
    df_lastgame = get_prior_matches(team_name, season_num, cur_timestamp, 1)
    
    return get_mean_value_by_team(df_lastgame, team_name, 'leaguerank')

In [99]:
df['away_prior_leaguerank'] = df.apply(get_prior_away_leaguerank, axis=1)

/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [91]:
get_values_by_team(df_ars_1, 'Arsenal', 'leaguerank')

[9,
 17,
 17,
 11,
 9,
 8,
 5,
 4,
 5,
 5,
 3,
 4,
 6,
 6,
 3,
 3,
 3,
 4,
 4,
 3,
 5,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4]

In [101]:
with open('PLmatches.csv', 'w') as open_file:
    df.to_csv(open_file)