In [13]:
import pandas as pd
import numpy as np
from math import isnan

In [14]:
with open('PLmatches.csv') as open_file:
    df = pd.read_csv(open_file, index_col=0)

In [15]:
def get_season_matches_by_stadium(match_stadium, season_num):
    all_season_matches = df[(df['match_stadium'] == match_stadium)
                           &(df['season_num'] == season_num)]
    
    return all_season_matches

def get_mean_value(data, col_name):
    values = []
    for row_index in data.index:
        values.append(data.loc[row_index, col_name])
    
    return np.mean(values)

In [16]:
def get_stadium_mean_attendance_delta(row):
    match_stadium = row['match_stadium']
    season_num = row['season_num']
    
    df_allgames = get_season_matches_by_stadium(match_stadium, season_num)
    
    cur_attendance = row['match_attendance']
    mean_attendance = np.mean(get_mean_value(df_allgames, 'match_attendance'))
    
    return cur_attendance - mean_attendance

In [17]:
df['mean_attendance_delta'] = df.apply(get_stadium_mean_attendance_delta, axis=1)

In [11]:
df.dropna(subset=['mean_attendance_delta'])

,hometeam_name,awayteam_name,home_goals,away_goals,match_date,match_timestamp,match_referee,match_stadium,match_attendance,home_possession,...,home_leaguepts,away_leaguepts,matchweek,stadium_capacity,season_num,home_prior_leaguerank,away_prior_leaguerank,attendance_delta,mean_attendance_delta_std,mean_attendance_delta
5567,Arsenal,Aston Villa,1,1,Sat 19 Aug 2006,1155996000000,Graham Poll,"Emirates Stadium, London",60023.0,72.9,...,1,1,1,59867,1,NaN,NaN,NaN,NaN,-22.6316
5568,Bolton Wanderers,Tottenham Hotspur,2,0,Sat 19 Aug 2006,1156004100000,Phil Dowd,"Macron Stadium, Bolton",22899.0,37.8,...,3,0,1,28723,1,NaN,NaN,NaN,NaN,-687.316
5569,Everton,Watford,2,1,Sat 19 Aug 2006,1155996000000,Peter Walton,"Goodison Park, Liverpool",39691.0,47.0,...,3,0,1,39572,1,NaN,NaN,NaN,NaN,2952.21
5570,Newcastle United,Wigan Athletic,2,1,Sat 19 Aug 2006,1155996000000,Martin Atkinson,"Sports Direct Arena, Newcastle",52227.0,55.3,...,3,0,1,52354,1,NaN,NaN,NaN,NaN,1253
5571,Portsmouth,Blackburn Rovers,3,0,Sat 19 Aug 2006,1155996000000,Alan Wiley,"Fratton Park, Portsmouth",19502.0,44.3,...,3,0,1,19699,1,NaN,NaN,NaN,NaN,-340.895
5572,Reading,Middlesbrough,3,2,Sat 19 Aug 2006,1155996000000,Mark Halsey,"Madejski Stadium, Reading",23802.0,52.1,...,3,0,1,24161,1,NaN,NaN,NaN,NaN,38.3158
5573,Sheffield United,Liverpool,1,1,Sat 19 Aug 2006,1155987900000,Rob Styles,"Bramall Lane, Sheffield",31726.0,41.9,...,1,1,1,32702,1,NaN,NaN,NaN,NaN,1045.58
5574,West Ham United,Charlton Athletic,3,1,Sat 19 Aug 2006,1155996000000,Howard Webb,"Boleyn Ground, London",34704.0,62.4,...,3,0,1,35016,1,NaN,NaN,NaN,NaN,117.947
5575,Chelsea,Manchester City,3,0,Sun 20 Aug 2006,1156086000000,Steve Bennett,"Stamford Bridge, London",41814.0,58.1,...,3,0,1,41631,1,NaN,NaN,NaN,NaN,263.053
5576,Manchester United,Fulham,5,1,Sun 20 Aug 2006,1156077000000,Andre Marriner,"Old Trafford, Manchester",75115.0,65.0,...,3,0,1,74994,1,NaN,NaN,NaN,NaN,-706.053
5577,Tottenham Hotspur,Sheffield United,2,0,Tue 22 Aug 2006,1156273200000,Peter Walton,"White Hart Lane, London",35287.0,56.1,...,3,1,2,36284,1,17.0,12.0,NaN,NaN,-515.737
5578,Watford,West Ham United,1,1,Tue 22 Aug 2006,1156272300000,Martin Atkinson,"Vicarage Road, Watford",18344.0,52.5,...,1,4,2,21577,1,14.0,4.0,NaN,NaN,-547.947
5579,Aston Villa,Reading,2,1,Wed 23 Aug 2006,1156358700000,Lee Mason,"Villa Park, Birmingham",37329.0,56.7,...,4,3,2,42682,1,10.0,6.0,NaN,NaN,1091.05
5580,Blackburn Rovers,Everton,1,1,Wed 23 Aug 2006,1156359600000,Uriah Rennie,"Ewood Park, Blackburn",22015.0,47.9,...,1,4,2,31367,1,18.0,7.0,NaN,NaN,753.474
5581,Charlton Athletic,Manchester United,0,3,Wed 23 Aug 2006,1156359600000,Chris Foy,"The Valley, London",25412.0,40.7,...,0,6,2,27111,1,16.0,1.0,NaN,NaN,-782.632
5582,Fulham,Bolton Wanderers,1,1,Wed 23 Aug 2006,1156359600000,Alan Wiley,"Craven Cottage, London",18559.0,61.1,...,1,4,2,25700,1,20.0,5.0,NaN,NaN,-3682.21
5583,Manchester City,Portsmouth,0,0,Wed 23 Aug 2006,1156358700000,Dermot Gallagher,"Etihad Stadium, Manchester",37214.0,53.9,...,1,4,2,55097,1,19.0,3.0,NaN,NaN,-2773.68
5584,Middlesbrough,Chelsea,2,1,Wed 23 Aug 2006,1156359600000,Howard Webb,"Riverside Stadium, Middlesbrough",29269.0,46.4,...,3,3,2,34000,1,13.0,2.0,NaN,NaN,1540.21
5585,Charlton Athletic,Bolton Wanderers,2,0,Sat 26 Aug 2006,1156600800000,Mike Dean,"The Valley, London",23673.0,42.9,...,3,4,3,27111,1,20.0,4.0,-1739.0,-1739.000000,-2521.63
5586,Fulham,Sheffield United,1,0,Sat 26 Aug 2006,1156600800000,Graham Poll,"Craven Cottage, London",18312.0,61.0,...,4,1,3,25700,1,18.0,15.0,-247.0,-247.000000,-3929.21
5587,Liverpool,West Ham United,2,1,Sat 26 Aug 2006,1156592700000,Alan Wiley,"Anfield, Liverpool",45262.0,54.7,...,4,4,3,54074,1,11.0,3.0,NaN,NaN,461.263
5588,Manchester City,Arsenal,1,0,Sat 26 Aug 2006,1156608900000,Uriah Rennie,"Etihad Stadium, Manchester",40699.0,37.8,...,4,1,3,55097,1,17.0,9.0,3485.0,3485.000000,711.316
5589,Tottenham Hotspur,Everton,0,2,Sat 26 Aug 2006,1156600800000,Mark Halsey,"White Hart Lane, London",35540.0,56.3,...,3,7,3,36284,1,11.0,6.0,253.0,253.000000,-262.737
5590,Watford,Manchester United,1,2,Sat 26 Aug 2006,1156600800000,Phil Dowd,"Vicarage Road, Watford",19453.0,40.5,...,1,9,3,21577,1,14.0,1.0,1109.0,1109.000000,561.053
5591,Wigan Athletic,Reading,1,0,Sat 26 Aug 2006,1156600800000,Mike Riley,"DW Stadium, Wigan",14834.0,48.1,...,3,3,3,25138,1,15.0,10.0,NaN,NaN,-3603.05
5592,Aston Villa,Newcastle United,2,0,Sun 27 Aug 2006,1156683600000,Howard Webb,"Villa Park, Birmingham",35141.0,45.2,...,7,3,3,42682,1,5.0,8.0,-2188.0,-2188.000000,-1096.95
5593,Blackburn Rovers,Chelsea,0,2,Sun 27 Aug 2006,1156690800000,Mark Clattenburg,"Ewood Park, Blackburn",19398.0,47.8,...,1,6,3,31367,1,16.0,7.0,-2617.0,-2617.000000,-1863.53
5594,Middlesbrough,Portsmouth,0,4,Mon 28 Aug 2006,1156791600000,Chris Foy,"Riverside Stadium, Middlesbrough",24834.0,64.2,...,3,7,3,34000,1,9.0,2.0,-4435.0,-4435.000000,-2894.79
5595,Arsenal,Middlesbrough,1,1,Sat 9 Sep 2006,1157810400000,Rob Styles,"Emirates Stadium, London",60007.0,69.2,...,2,4,4,59867,1,17.0,16.0,-16.0,-16.000000,-38.6316
5596,Bolton Wanderers,Watford,1,0,Sat 9 Sep 2006,1157810400000,Mark Clattenburg,"Macron Stadium, Bolton",21140.0,53.8,...,7,1,4,28723,1,8.0,18.0,-1759.0,-1759.000000,-2446.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Burnley,Brighton and Hove Albion,0,0,Sat 28 Apr 2018,1524924000000,Roger East,"Turf Moor, Burnley",19459.0,44.5,...,54,37,36,21401,12,7.0,13.0,-1805.0,-1299.882353,-1229.42
22693,Crystal Palace,Leicester City,5,0,Sat 28 Apr 2018,1524924000000,Mike Dean,"Selhurst Park, London",25750.0,50.5,...,38,44,36,26074,12,14.0,8.0,1094.0,745.176471,687.421
22694,Huddersfield Town,Everton,0,2,Sat 28 Apr 2018,1524924000000,Lee Probert,"John Smith's Stadium, Huddersfield",24121.0,53.7,...,35,48,36,24121,12,15.0,8.0,160.0,99.882353,89.3158
22695,Liverpool,Stoke City,0,0,Sat 28 Apr 2018,1524915000000,Andre Marriner,"Anfield, Liverpool",53255.0,71.9,...,72,30,36,54074,12,3.0,19.0,296.0,83.000000,206
22696,Manchester United,Arsenal,2,1,Sun 29 Apr 2018,1525015800000,Kevin Friend,"Old Trafford, Manchester",75035.0,59.2,...,77,57,36,74994,12,2.0,6.0,-60.0,67.117647,59.3158
22697,Newcastle United,West Bromwich Albion,0,1,Sat 28 Apr 2018,1524924000000,David Coote,"St. James' Park, Newcastle",52283.0,63.5,...,41,28,36,52354,12,10.0,20.0,73.0,326.117647,291.211
22698,Southampton,AFC Bournemouth,2,1,Sat 28 Apr 2018,1524924000000,Anthony Taylor,"St. Mary's Stadium, Southampton",31778.0,40.3,...,32,38,36,32505,12,18.0,11.0,14.0,1106.000000,984.105
22699,Swansea City,Chelsea,0,1,Sat 28 Apr 2018,1524933000000,Jonathan Moss,"Liberty Stadium, Swansea",20900.0,51.1,...,33,66,36,21088,12,17.0,5.0,-33.0,312.562500,277.368
22700,Tottenham Hotspur,Watford,2,0,Mon 30 Apr 2018,1525114800000,Michael Oliver,"Wembley Stadium, London",52675.0,61.5,...,71,38,36,90000,12,4.0,12.0,-28136.0,-16546.812500,-15377
22701,West Ham United,Manchester City,1,4,Sun 29 Apr 2018,1525007700000,Neil Swarbrick,"London Stadium, London",56904.0,24.6,...,35,93,36,57000,12,15.0,1.0,109.0,24.250000,19.3684
22702,Arsenal,Burnley,5,0,Sun 6 May 2018,1525620600000,Andre Marriner,"Emirates Stadium, London",59540.0,63.6,...,60,54,37,59867,12,6.0,7.0,118.0,229.277778,217.211
22703,AFC Bournemouth,Swansea City,1,0,Sat 5 May 2018,1525528800000,Kevin Friend,"Vitality Stadium, Bournemouth",10820.0,45.2,...,41,33,37,11360,12,12.0,17.0,-132.0,189.222222,179.263
22704,Brighton and Hove Albion,Manchester United,1,0,Fri 4 May 2018,1525460400000,Craig Pawson,"Amex Stadium, Falmer",30611.0,31.7,...,40,78,37,30750,12,14.0,2.0,171.0,219.888889,208.316
22705,Chelsea,Liverpool,1,0,Sun 6 May 2018,1525620600000,Anthony Taylor,"Stamford Bridge, London",41314.0,31.6,...,70,72,37,41631,12,5.0,3.0,-10.0,-105.352941,32.2632
22706,Everton,Southampton,1,1,Sat 5 May 2018,1525537800000,Jonathan Moss,"Goodison Park, Liverpool",38225.0,54.4,...,49,36,37,39572,12,8.0,18.0,-836.0,-603.777778,-572
22707,Leicester City,West Ham United,0,2,Sat 5 May 2018,1525528800000,Chris Kavanagh,"King Power Stadium, Leicester",32013.0,54.0,...,47,39,37,32312,12,9.0,15.0,853.0,426.235294,377.053
22708,Manchester City,Huddersfield Town,0,0,Sun 6 May 2018,1525609800000,Mike Dean,"Etihad Stadium, Manchester",54350.0,79.2,...,97,37,37,55097,12,1.0,16.0,-37.0,302.625000,287.722
22709,Stoke City,Crystal Palace,1,2,Sat 5 May 2018,1525519800000,Martin Atkinson,"bet365 Stadium, Stoke",29687.0,41.1,...,30,41,37,30089,12,19.0,11.0,155.0,429.777778,407.158
22710,Watford,Newcastle United,2,1,Sat 5 May 2018,1525528800000,Roger East,"Vicarage Road, Watford",20375.0,39.2,...,41,41,37,21577,12,13.0,10.0,-26.0,152.055556,144.053
22711,West Bromwich Albion,Tottenham Hotspur,1,0,Sat 5 May 2018,1525528800000,Mike Jones,"The Hawthorns, West Bromwich",23685.0,26.2,...,31,74,37,26688,12,20.0,4.0,-835.0,-881.277778,-834.895
22712,Burnley,AFC Bournemouth,1,2,Sun 13 May 2018,1526220000000,Paul Tierney,"Turf Moor, Burnley",20720.0,51.4,...,54,44,38,21401,12,7.0,12.0,1261.0,33.333333,31.5789
22713,Crystal Palace,West Bromwich Albion,2,0,Sun 13 May 2018,1526220000000,Jonathan Moss,"Selhurst Park, London",25357.0,59.2,...,44,31,38,26074,12,11.0,19.0,-393.0,310.777778,294.421
22714,Huddersfield Town,Arsenal,0,1,Sun 13 May 2018,1526220000000,Michael Oliver,"John Smith's Stadium, Huddersfield",24122.0,45.0,...,37,63,38,24121,12,16.0,6.0,1.0,95.333333,90.3158
22715,Liverpool,Brighton and Hove Albion,4,0,Sun 13 May 2018,1526220000000,Kevin Friend,"Anfield, Liverpool",50752.0,72.3,...,75,40,38,54074,12,4.0,14.0,-2503.0,-2424.611111,-2297
22716,Manchester United,Watford,1,0,Sun 13 May 2018,1526220000000,Lee Mason,"Old Trafford, Manchester",75049.0,51.4,...,81,41,38,74994,12,2.0,13.0,14.0,77.388889,73.3158
22717,Newcastle United,Chelsea,3,0,Sun 13 May 2018,1526220000000,Martin Atkinson,"St. James' Park, Newcastle",52294.0,41.9,...,44,70,38,52354,12,10.0,5.0,11.0,319.000000,302.211
22718,Southampton,Manchester City,0,1,Sun 13 May 2018,1526220000000,Andre Marriner,"St. Mary's Stadium, Southampton",31882.0,30.3,...,36,100,38,32505,12,17.0,1.0,104.0,1148.555556,1088.11
22719,Swansea City,Stoke City,1,2,Sun 13 May 2018,1526220000000,Anthony Taylor,"Liberty Stadium, Swansea",20673.0,57.6,...,33,33,38,21088,12,18.0,20.0,-185.0,53.166667,50.3684
22720,Tottenham Hotspur,Leicester City,5,4,Sun 13 May 2018,1526220000000,Craig Pawson,"Wembley Stadium, London",77841.0,64.0,...,77,47,38,90000,12,3.0,9.0,22918.0,10332.833333,9789
22721,West Ham United,Everton,3,1,Sun 13 May 2018,1526220000000,Graham Scott,"London Stadium, London",56926.0,56.6,...,42,49,38,57000,12,15.0,8.0,24.0,43.666667,41.3684

In [19]:
with open('PLmatches.csv', 'w') as open_file:
    df.to_csv(open_file)

In [18]:
df['mean_attendance_delta']

5567       -22.631579
5568      -687.315789
5569      2952.210526
5570      1253.000000
5571      -340.894737
5572        38.315789
5573      1045.578947
5574       117.947368
5575       263.052632
5576      -706.052632
5577      -515.736842
5578      -547.947368
5579      1091.052632
5580       753.473684
5581      -782.631579
5582     -3682.210526
5583     -2773.684211
5584      1540.210526
5585     -2521.631579
5586     -3929.210526
5587       461.263158
5588       711.315789
5589      -262.736842
5590       561.052632
5591     -3603.052632
5592     -1096.947368
5593     -1863.526316
5594     -2894.789474
5595       -38.631579
5596     -2446.315789
             ...
22692    -1229.421053
22693      687.421053
22694       89.315789
22695      206.000000
22696       59.315789
22697      291.210526
22698      984.105263
22699      277.368421
22700   -15377.000000
22701       19.368421
22702      217.210526
22703      179.263158
22704      208.315789
22705       32.263158
22706     -572.000000
22707      377.052632
22708      287.722222
22709      407.157895
22710      144.052632
22711     -834.894737
22712       31.578947
22713      294.421053
22714       90.315789
22715    -2297.000000
22716       73.315789
22717      302.210526
22718     1088.105263
22719       50.368421
22720     9789.000000
22721       41.368421
Name: mean_attendance_delta, Length: 4559, dtype: float64