In [5]:
import pandas as pd
import numpy as np
from math import isnan

In [6]:
with open('PLmatches.csv') as open_file:
    df = pd.read_csv(open_file, index_col=0)

In [19]:
def get_prior_matches(team_name, season_num, match_timestamp, num_matches=38):
    all_prior_matches = df[((df['hometeam_name'] == team_name)|(df['awayteam_name'] == team_name))
                           #&(df['season_num'] == season_num)
                          &(df['match_timestamp'] < match_timestamp)].sort_values(by='match_timestamp')
    
    return all_prior_matches[-num_matches:]

,hometeam_name,awayteam_name,home_goals,away_goals,match_date,match_timestamp,match_referee,match_stadium,match_attendance,home_possession,...,home_leaguepts,away_leaguepts,matchweek,stadium_capacity,season_num,home_prior_leaguerank,away_prior_leaguerank,attendance_delta,mean_attendance_delta_std,mean_attendance_delta
9969,Arsenal,Swansea City,0,1,Mon 11 May 2015,1431370800000,Kevin Friend,"Emirates Stadium, London",59989.0,67.9,...,70,56,36,59867,9,3.0,8.0,-77.0,-4.500000,-2.736842
9977,Manchester United,Arsenal,1,1,Sun 17 May 2015,1431874800000,Mike Dean,"Old Trafford, Manchester",75323.0,57.4,...,69,72,37,74994,9,4.0,3.0,-131.0,-12.500000,-11.842105
9980,Arsenal,Sunderland,0,0,Wed 20 May 2015,1432147500000,Anthony Taylor,"Emirates Stadium, London",59987.0,75.1,...,72,38,37,59867,9,3.0,15.0,-2.0,-6.235294,-4.736842
9981,Arsenal,West Bromwich Albion,4,1,Sun 24 May 2015,1432476000000,Robert Madley,"Emirates Stadium, London",59971.0,63.7,...,75,44,38,59867,9,3.0,13.0,-16.0,-21.888889,-20.736842
12121,Arsenal,West Ham United,0,2,Sun 9 Aug 2015,1439123400000,Martin Atkinson,"Emirates Stadium, London",59996.0,61.8,...,0,3,1,59867,10,NaN,NaN,NaN,NaN,52.105263
12132,Crystal Palace,Arsenal,1,2,Sun 16 Aug 2015,1439728200000,Lee Mason,"Selhurst Park, London",24732.0,40.8,...,3,3,2,26074,10,3.0,19.0,NaN,NaN,96.052632
12144,Arsenal,Liverpool,0,0,Mon 24 Aug 2015,1440442800000,Michael Oliver,"Emirates Stadium, London",60080.0,65.7,...,4,7,3,59867,10,11.0,3.0,84.0,84.000000,136.105263
12150,Newcastle United,Arsenal,0,1,Sat 29 Aug 2015,1440848700000,Andre Marriner,"St. James' Park, Newcastle",50388.0,26.3,...,2,7,4,52354,10,17.0,9.0,1369.0,1369.000000,634.473684
12155,Arsenal,Stoke City,2,0,Sat 12 Sep 2015,1442066400000,Jonathan Moss,"Emirates Stadium, London",59963.0,67.6,...,10,2,5,59867,10,6.0,18.0,-117.0,-75.000000,19.105263
12167,Chelsea,Arsenal,2,0,Sat 19 Sep 2015,1442663100000,Mike Dean,"Stamford Bridge, London",41584.0,62.9,...,7,10,6,41631,10,17.0,4.0,3.0,177.500000,83.684211
12175,Leicester City,Arsenal,2,5,Sat 26 Sep 2015,1443276000000,Craig Pawson,"King Power Stadium, Leicester",32047.0,42.0,...,12,13,7,32312,10,4.0,5.0,314.0,65.000000,26.315789
12192,Arsenal,Manchester United,3,0,Sun 4 Oct 2015,1443970800000,Anthony Taylor,"Emirates Stadium, London",60084.0,37.8,...,16,16,8,59867,10,4.0,1.0,121.0,71.000000,140.105263
12201,Watford,Arsenal,0,3,Sat 17 Oct 2015,1445099400000,Mike Jones,"Vicarage Road, Watford",20721.0,33.3,...,10,19,9,21577,10,12.0,2.0,553.0,620.500000,127.263158
12205,Arsenal,Everton,2,1,Sat 24 Oct 2015,1445704200000,Lee Mason,"Emirates Stadium, London",59985.0,56.2,...,22,13,10,59867,10,2.0,9.0,-99.0,-45.750000,41.105263
12219,Swansea City,Arsenal,0,3,Sat 31 Oct 2015,1446303600000,Kevin Friend,"Liberty Stadium, Swansea",20937.0,54.2,...,13,25,11,21088,10,12.0,2.0,893.0,297.000000,226.052632
12232,Arsenal,Tottenham Hotspur,1,1,Sun 8 Nov 2015,1446998400000,Martin Atkinson,"Emirates Stadium, London",60060.0,54.9,...,26,21,12,59867,10,2.0,5.0,75.0,38.400000,116.105263
12242,West Bromwich Albion,Arsenal,2,1,Sat 21 Nov 2015,1448118000000,Mark Clattenburg,"The Hawthorns, West Bromwich",24343.0,27.0,...,17,26,13,26688,10,13.0,2.0,193.0,226.333333,-288.315789
12252,Norwich City,Arsenal,1,1,Sun 29 Nov 2015,1448813700000,Jonathan Moss,"Carrow Road, Norwich",27091.0,36.8,...,13,27,14,27244,10,16.0,4.0,62.0,107.000000,118.894737
12255,Arsenal,Sunderland,3,1,Sat 5 Dec 2015,1449327600000,Robert Madley,"Emirates Stadium, London",59937.0,72.5,...,30,12,15,59867,10,4.0,17.0,-123.0,-91.000000,-6.894737
12271,Aston Villa,Arsenal,0,2,Sun 13 Dec 2015,1450013400000,Kevin Friend,"Villa Park, Birmingham",33285.0,45.8,...,6,33,16,42682,10,20.0,2.0,-1772.0,-2750.285714,-405.105263
12284,Arsenal,Manchester City,2,1,Mon 21 Dec 2015,1450728000000,Andre Marriner,"Emirates Stadium, London",60053.0,37.3,...,36,32,17,59867,10,2.0,3.0,116.0,38.000000,109.105263
12291,Southampton,Arsenal,4,0,Sat 26 Dec 2015,1451159100000,Jonathan Moss,"St. Mary's Stadium, Southampton",31669.0,35.2,...,24,36,18,32505,10,12.0,2.0,33.0,963.888889,918.157895
12295,Arsenal,AFC Bournemouth,2,0,Mon 28 Dec 2015,1451323800000,Roger East,"Emirates Stadium, London",59983.0,51.4,...,39,20,19,59867,10,2.0,14.0,-70.0,-36.750000,39.105263
12305,Arsenal,Newcastle United,1,0,Sat 2 Jan 2016,1451746800000,Anthony Taylor,"Emirates Stadium, London",59257.0,51.0,...,42,17,20,59867,10,1.0,18.0,-726.0,-758.666667,-686.894737
12319,Liverpool,Arsenal,3,3,Wed 13 Jan 2016,1452715200000,Mike Jones,"Anfield, Liverpool",44109.0,59.5,...,31,43,21,54074,10,8.0,1.0,-14.0,48.666667,199.263158
12333,Stoke City,Arsenal,0,0,Sun 17 Jan 2016,1453047300000,Craig Pawson,"bet365 Stadium, Stoke",27683.0,45.0,...,33,44,22,30089,10,7.0,1.0,409.0,244.400000,148.894737
12343,Arsenal,Chelsea,0,1,Sun 24 Jan 2016,1453651200000,Mark Clattenburg,"Emirates Stadium, London",60072.0,46.6,...,44,28,23,59867,10,1.0,14.0,815.0,132.200000,128.105263
12345,Arsenal,Southampton,0,0,Tue 2 Feb 2016,1454442300000,Lee Mason,"Emirates Stadium, London",60044.0,66.7,...,45,34,24,59867,10,3.0,8.0,-28.0,92.181818,100.105263
12363,AFC Bournemouth,Arsenal,0,2,Sun 7 Feb 2016,1454851800000,Kevin Friend,"Goldsands Stadium, Bournemouth",11357.0,50.7,...,28,48,25,11360,10,15.0,4.0,292.0,159.636364,168.263158
12372,Arsenal,Leicester City,2,1,Sun 14 Feb 2016,1455451200000,Martin Atkinson,"Emirates Stadium, London",60009.0,72.1,...,51,53,26,59867,10,3.0,1.0,-35.0,49.500000,65.105263

In [9]:
def get_mean_value_by_team(data, team_name, col_name):
    values = []
    for row_index in data.index:
        if data.loc[row_index, 'hometeam_name'] != team_name and data.loc[row_index, 'awayteam_name'] != team_name:
            continue
        team_loc = 'home' if data.loc[row_index, 'hometeam_name'] == team_name else 'away'
        values.append(data.loc[row_index, '_'.join([team_loc, col_name])])
    
    return np.mean(values)

def get_values_by_team(data, team_name, col_name):
    values = []
    for row_index in data.index:
        if data.loc[row_index, 'hometeam_name'] != team_name and data.loc[row_index, 'awayteam_name'] != team_name:
            continue
        team_loc = 'home' if data.loc[row_index, 'hometeam_name'] == team_name else 'away'
        values.append(data.loc[row_index, '_'.join([team_loc, col_name])])
    
    return values

In [56]:
def get_prior_home_goals(row):
    team_name = row['hometeam_name']
    season_num = row['season_num']
    cur_timestamp = row['match_timestamp']
    
    df_lastgame = get_prior_matches(team_name, season_num, cur_timestamp, 1)
    
    return get_mean_value_by_team(df_lastgame, team_name, 'goals')

def get_prior_away_goals(row):
    team_name = row['awayteam_name']
    season_num = row['season_num']
    cur_timestamp = row['match_timestamp']
    
    df_lastgame = get_prior_matches(team_name, season_num, cur_timestamp, 1)
    
    return get_mean_value_by_team(df_lastgame, team_name, 'goals')

In [57]:
df['home_prior_goals'] = df.apply(get_prior_home_goals, axis=1)

/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [58]:
df['away_prior_goals'] = df.apply(get_prior_away_goals, axis=1)

/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/dlahtou/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [60]:
with open('PLmatches.csv', 'w') as open_file:
    df.to_csv(open_file)

In [59]:
df[(df['season_num'] == 4)&(df['matchweek'] == 1)]

,hometeam_name,awayteam_name,home_goals,away_goals,match_date,match_timestamp,match_referee,match_stadium,match_attendance,home_possession,...,matchweek,stadium_capacity,season_num,home_prior_leaguerank,away_prior_leaguerank,attendance_delta,mean_attendance_delta_std,mean_attendance_delta,home_prior_goals,away_prior_goals
6707,Aston Villa,Wigan Athletic,0,2,Sat 15 Aug 2009,1250344800000,Mark Clattenburg,"Villa Park, Birmingham",35578.0,47.0,...,1,42682,4,6.0,11.0,NaN,NaN,-2995.421053,1.0,1.0
6708,Blackburn Rovers,Manchester City,0,2,Sat 15 Aug 2009,1250344800000,Mike Dean,"Ewood Park, Blackburn",29584.0,43.5,...,1,31367,4,15.0,10.0,NaN,NaN,4155.842105,0.0,1.0
6709,Bolton Wanderers,Sunderland,0,1,Sat 15 Aug 2009,1250344800000,Andre Marriner,"Macron Stadium, Bolton",22247.0,54.3,...,1,28723,4,13.0,16.0,NaN,NaN,366.105263,0.0,2.0
6710,Chelsea,Hull City,2,1,Sat 15 Aug 2009,1250336700000,Alan Wiley,"Stamford Bridge, London",41597.0,67.6,...,1,41631,4,3.0,17.0,NaN,NaN,174.421053,3.0,0.0
6711,Everton,Arsenal,1,6,Sat 15 Aug 2009,1250353800000,Mark Halsey,"Goodison Park, Liverpool",39309.0,45.7,...,1,39572,4,5.0,4.0,NaN,NaN,NaN,2.0,4.0
6712,Portsmouth,Fulham,0,1,Sat 15 Aug 2009,1250344800000,Martin Atkinson,"Fratton Park, Portsmouth",17510.0,55.1,...,1,19699,4,14.0,7.0,NaN,NaN,-739.315789,0.0,0.0
6713,Stoke City,Burnley,2,0,Sat 15 Aug 2009,1250344800000,Steve Bennett,"bet365 Stadium, Stoke",27385.0,37.7,...,1,30089,4,12.0,NaN,NaN,NaN,NaN,1.0,NaN
6714,Wolverhampton Wanderers,West Ham United,0,2,Sat 15 Aug 2009,1250344800000,Chris Foy,"Molineux Stadium, Wolverhampton",28674.0,48.6,...,1,31700,4,NaN,9.0,NaN,NaN,308.263158,NaN,2.0
6715,Manchester United,Birmingham City,1,0,Sun 16 Aug 2009,1250425800000,Lee Mason,"Old Trafford, Manchester",75062.0,63.0,...,1,74994,4,1.0,19.0,NaN,NaN,197.578947,1.0,4.0
6716,Tottenham Hotspur,Liverpool,2,1,Sun 16 Aug 2009,1250434800000,Phil Dowd,"White Hart Lane, London",35935.0,47.5,...,1,36284,4,8.0,2.0,NaN,NaN,140.736842,1.0,3.0